package Exception;

public class Erro1 {
    public static void main(String[] args) {
        int[] vetor = new int[4];
        System.out.println("Antes da exception");


    }
}
